WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/config/routes.rb
BookWriter::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'books#index'

  devise_for :users

  post '/filterbooksadv', to: 'books#filterBooksAdv', :defaults => { :format => 'json' }
  post '/filterbookssimple', to: 'books#filterBooksSimple', :defaults => { :format => 'json' }

  resources :books do
    get 'print', :on => :member
    post 'close', :on => :member
    get 'new_edition', :on => :member
    resources :chunks, :except => [:index]
  end

end

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  # :recoverable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  attr_accessible :login
  attr_accessor :login

  has_and_belongs_to_many :books
  has_many :chunks

  validates_presence_of :first_name, :last_name
  validates :username, :uniqueness => {:case_sensitive => false}

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {:value => login.downcase}]).first
    else
      where(conditions).first
    end
  end

end

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/controllers/users_controller.rb
class UsersController < ApplicationController
=begin
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: I18n.t('views.user.flash_messages.book_was_successfully_created') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: I18n.t('views.user.flash_messages.book_was_successfully_updated') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
=end
end

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/helpers/users_helper.rb
module UsersHelper
end

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Vorname" %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label "Nachname" %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit "Speichern" %>
  </div>
<% end %>

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/views/users/edit.html.erb
<h1>Benutzerdaten ändern</h1>

<%= render 'form' %>

<%= button_to 'Zurück', books_path, :method => :get %>

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/views/users/show.html.erb
<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>