WebEngProjekt_GemeinsamEinfallslos/config/routes.rb
WebEngProjektGemeinsameinfallslos::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'books#index'
  resources :books do
    resources :chunks
  end
  devise_for :users

end

WebEngProjekt_GemeinsamEinfallslos/app/models/chunk.rb
class Chunk < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
  attr_accessible :content, :section, :title, :user_id, :original_updated_at
  attr_writer :original_updated_at
  validates :section, :title, :user_id, :original_updated_at, presence: true
  validate :handle_conflict, only: :update
  validates_format_of :section, :with => /^[1-9](\.\d(\.\d)?)?$/, :message => "must look like '2[.3[.4]]'"

  has_paper_trail

  def username
    user.email
  end

  def original_updated_at
    @original_updated_at || updated_at.to_f
  end

  def handle_conflict
    if @conflict || updated_at.to_f > original_updated_at.to_f
      @conflict = true
      @original_updated_at = nil
      errors.add :base, 'Content was modified by another user. Please merge the changes!'
      changes.each do |attribute, values|
        unless attribute == 'content'
          errors.add attribute, "was changed to #{values.first}."
        else
          errors.add attribute, 'was changed.'
          self.content = '== CONTENT OF OTHER USER =='
          self.content << values.first
          self.content << '== YOUR CONTENT =='
          self.content << values.last
        end
      end
    end
  end

end

WebEngProjekt_GemeinsamEinfallslos/app/controllers/chunks_controller.rb
class ChunksController < ApplicationController
  layout 'books_and_chunks'
  before_filter :authenticate_user!
  before_filter :find_book

  # GET /chunks
  # GET /chunks.json
  def index
    @chunks = Chunk.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chunks }
    end
  end

  # GET /chunks/1
  # GET /chunks/1.json
  def show
    @chunk = Chunk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chunk }
    end
  end

  # GET /chunks/new
  # GET /chunks/new.json
  def new
    @chunk = Chunk.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chunk }
    end
  end

  # GET /chunks/1/edit
  def edit
    @chunk = Chunk.find(params[:id])

    render_check_template
  end

  # POST /chunks
  # POST /chunks.json
  def create
    @chunk = Chunk.new(params[:chunk])
    @chunk.book = @book

    respond_to do |format|
      if @chunk.save
        format.html { redirect_to @book, notice: 'Chunk was successfully created.' }
        format.json { render json: @chunk, status: :created, location: @chunk }
      else
        format.html { render action: "new" }
        format.json { render json: @chunk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chunks/1
  # PUT /chunks/1.json
  def update
    @chunk = Chunk.find(params[:id])

    respond_to do |format|
      if @chunk.update_attributes(params[:chunk])
        format.html { redirect_to @book, notice: 'Chunk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chunk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chunks/1
  # DELETE /chunks/1.json
  def destroy
    @chunk = Chunk.find(params[:id])
    @chunk.destroy

    respond_to do |format|
      format.html { redirect_to @book }
      format.json { head :no_content }
    end
  end

  # Das richtige Buch zuordnen
  private
  def find_book
    @book = Book.find(params[:book_id])
  end
end

WebEngProjekt_GemeinsamEinfallslos/app/views/chunks/_form.html.erb
<%= form_for([@book, @chunk]) do |f| %>
  <% if @chunk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chunk.errors.count, "error") %> prohibited this chunk from being saved:</h2>

      <ul>
      <% @chunk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :original_updated_at %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :section %><b   r />
    <%= f.text_field :section %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.collection_select(:user_id, User.all, :id, :email) %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.cktext_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

WebEngProjekt_GemeinsamEinfallslos/app/views/chunks/edit.html.erb
<h1>Editing chunk</h1>

<%= render 'form' %>

<%= button_to 'Back', @book, method: :get %>

WebEngProjekt_GemeinsamEinfallslos/app/views/chunks/index.html.erb
<h1>Listing chunks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Section</th>
    <th>Content</th>
    <th>User</th>
    <th>Book</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chunks.each do |chunk| %>
  <tr>
    <td><%= chunk.title %></td>
    <td><%= chunk.section %></td>
    <td><%= chunk.content %></td>
    <td><%= chunk.user %></td>
    <td><%= chunk.book %></td>
    <td><%= link_to 'Show', chunk %></td>
    <td><%= link_to 'Edit', edit_chunk_path(chunk) %></td>
    <td><%= link_to 'Destroy', chunk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chunk', new_chunk_path %>

WebEngProjekt_GemeinsamEinfallslos/app/views/chunks/new.html.erb
<h1>New chunk</h1>

<%= render 'form' %>

<%= button_to 'Back', @book, method: :get %>

WebEngProjekt_GemeinsamEinfallslos/app/views/chunks/show.html.erb
<h1><%= @chunk.title %></h1>
<br/>
<p>
  <b>Section:</b>
  <%= @chunk.section %>
</p>
<p>
  <b>Version:</b>
  <%= @chunk.version %>
</p>
<p>
  <b>User:</b>
  <%= @chunk.username %>
</p>
<p><%= raw @chunk.content %></p>
<%= button_to 'Back', @book, method: :get %>