WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/config/routes.rb
BookWriter::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'books#index'

  devise_for :users

  post '/filterbooksadv', to: 'books#filterBooksAdv', :defaults => { :format => 'json' }
  post '/filterbookssimple', to: 'books#filterBooksSimple', :defaults => { :format => 'json' }

  resources :books do
    get 'print', :on => :member
    post 'close', :on => :member
    get 'new_edition', :on => :member
    resources :chunks, :except => [:index]
  end

end

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/models/book.rb
class Book < ActiveRecord::Base

  attr_accessible :title, :edition, :published, :genre, :abstract, :tags, :user_ids, :closed

  has_and_belongs_to_many :users
  has_many :chunks

  validates_presence_of :title, :edition, :users
  validates :edition, :uniqueness => {:scope => :title}

  before_destroy :destroy_chunks

  def sliced_attributes
    attributes.slice('title', 'genre', 'abstract', 'tags')
  end

  def published?
    !published.nil?
  end

  def has_chunks?
    !chunks.empty?
  end

  def max_chunk_position
    has_chunks? ? chunks.max_by(&:position).position : 0
  end

  def users_list
    users.collect { |u| u.username }.join(',')
  end

  def users_list_real_names
    users.collect { |u| u.first_name + ' ' + u.last_name }.join(',')
  end

  private
  def destroy_chunks
    chunks.each do |chunk|
      chunk.destroy
    end
  end

  def self.search(search)
    search_condition = "%" + search + "%"

    find(:all, :include => :users, :conditions => ['title LIKE ? OR edition LIKE ? OR published LIKE ? OR tags LIKE ? OR genre LIKE ? OR users.username LIKE ?', search_condition, search_condition, search_condition, search_condition, search_condition, search_condition])
  end

  def self.searchAdv(search)
    search_obj = JSON.parse(search)
    sql_strings = {
      :title => { :contains => "title LIKE ?", :contains_not => "title NOT LIKE ?" },
      :edition => { :eq => "edition = ?", :neq => "edition != ?", :lt => "edition < ?", :gt => "edition > ?" },
      :published => { :before => "published < ?", :after => "published > ?" },
      :genre => { :contains => "genre LIKE ?", :contains_not => "genre NOT LIKE ?"},
      :tags => { :contains => "tags LIKE ?", :contains_not => "tags NOT LIKE ?"},
      :autor => { :contains => "users.username LIKE ?", :contains_not => "users.username NOT LIKE ?"}
    }

    sql_query_string = "1=1"
    sql_query_vars = []

    search_obj.each { |col, val|
      val.each { |col2, val2|
        if !(val2.empty?)
          sql_query_string += " AND #{sql_strings[col.to_sym][col2.to_sym]}"
          if col == "edition"
            sql_query_vars.push("#{val2.to_i}")
          elsif col == "published"
            sql_query_vars.push("#{val2.to_date}")
          else
            sql_query_vars.push("%#{val2}%")
          end
        end
      }
    }

    sql_query_vars.insert(0, sql_query_string)

    find(:all, :include => :users, :conditions => sql_query_vars)
  #  find(:all, :conditions => ['title LIKE ? AND title NOT LIKE ?
  #                            AND edition = ? OR NULL AND edition != ? AND edition < ? AND edition > ?
  #                            AND published < ? AND published > ?
  #                            AND genre LIKE ? AND genre NOT LIKE ?
  #                            AND tags LIKE ? AND tags NOT LIKE?',
  #                            "%#{search_obj["title"]["contains"]}%", "%#{search_obj["title"]["contains_not"]}%",
  #                            "%#{search_obj["edition"]["eq"]}%", "%#{search_obj["edition"]["neq"]}%", "%#{search_obj["edition"]["lt"]}%", "%#{search_obj["edition"]["gt"]}%",
  #                            "%#{search_obj["published"]["before"]}%", "%#{search_obj["published"]["after"]}%",
  #                            "%#{search_obj["genre"]["contains"]}%", "%#{search_obj["genre"]["contains_not"]}%",
  #                            "%#{search_obj["tags"]["contains"]}%", "%#{search_obj["tags"]["contains_not"]}%"])
  end
end

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/controllers/books_controller.rb
class BooksController < ApplicationController

  layout 'books_and_chunks'
  before_filter :authenticate_user!
  before_filter :find_all_users, :only => [:new, :edit, :new_edition]

  # GET /books
  # GET /books.json
  def index
    @books = current_user.books

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html { render_check_template }
      format.json { render json: @book }
    end
  end

  def print
    @book = Book.find(params[:id])

    respond_to do |format|
      format.pdf do
        render :pdf => @book.title, :layout => 'print'
      end
    end

  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])

    unless @book.closed?
      render_check_template
    else
      flash[:error] = I18n.t('views.book.flash_errors.book_is_closed')
      render_check_template 'show'
    end
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    old_book_id = session[:old_book_id]

    respond_to do |format|
      if @book.save
        unless old_book_id.nil?
          old_book = Book.find(old_book_id)
          old_book.chunks.each do |old_chunk|
            chunk = Chunk.new(old_chunk.sliced_attributes)
            chunk.book = @book
            chunk.save
            @book.chunks << chunk
          end
          session[:old_book_id] = nil
        end
        format.html { redirect_to @book, notice: I18n.t('views.book.flash_messages.book_was_successfully_created') }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html do
          @users ||= User.all
          render action: 'new'
        end
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    if params[:update_chunk_order_only] == 'true'
      chunk_ids = params[:chunk_order].split(',')
      chunk_ids.each_with_index do |chunk_id, i|
        chunk = Chunk.find(chunk_id)
        chunk.update_attribute(:position, i)
      end
    else
      params[:book][:user_ids] ||= []
    end

    respond_to do |format|
      if params[:update_chunk_order_only] == 'true'
        format.html { render 'show', layout: false }
      else
        if @book.update_attributes(params[:book])
          format.html { redirect_to @book, notice: I18n.t('views.book.flash_messages.book_was_successfully_updated') }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def close
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(:closed => true, :published => Time.now)
        format.html { redirect_to @book, notice: I18n.t('views.book.flash_messages.book_was_successfully_closed') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_edition
    old_book = Book.find(params[:id])
    @book = Book.new(old_book.sliced_attributes)
    @book.users = old_book.users

    session[:old_book_id] = old_book.id
    render 'new'
  end

# DELETE /books/1
# DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

# filter books. respond with json for ajax
  def filterBooksAdv
    # search code
    result_books = Book.searchAdv params[:search_obj]
    result_array = []
    result_books.each do |book|
      result_array.push(["<a class=\"tbl_link\" href=\"/books/#{book.id.to_s}\">" + book.title + "</a>", book.edition, book.published, book.genre, book.tags, book.users_list]);
    end

    respond_to do |format|
      format.json { render json: result_array.to_json }
    end
  end

  def filterBooksSimple
    # search code

    result_books = Book.search params[:query]
    result_array = []
    result_books.each do |book|
      result_array.push(["<a class=\"tbl_link\" href=\"/books/#{book.id.to_s}\">" + book.title + "</a>", book.edition, book.published, book.genre, book.tags, book.users_list]);
    end

    respond_to do |format|
      format.json { render json: result_array.to_json }
    end
  end

  private
  def find_all_users
    @users = User.all
  end

end

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/helpers/books_helper.rb
module BooksHelper
end

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
    <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= t 'activerecord.errors.template.header', :model => Book.model_name.human, :count => @book.errors.count %></h2>

          <ul>
            <% @book.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field input-group">
      <%= f.label :title %>
      <br/>
      <%= f.text_field :title, :class => "form-control" %>
    </div>
    <div class="field input-group">
      <%= f.label :edition %>
      <br/>
      <%= f.text_field :edition, :class => "form-control" %>
    </div>
    <div class="field input-group">
      <%= f.label :genre %>
      <br/>
      <%= f.text_field :genre, :class => "form-control" %>
    </div>
    <div class="field input-group">
      <%= f.label :abstract %>
      <br/>
      <%= f.cktext_area :abstract, :class => "form-control" %>
    </div>
    <div class="field input-group">
      <%= f.label :tags %>
      <br/>
      <%= f.text_field :tags, :class => "form-control" %>
    </div>
    <div class="field input-group">
      <%= f.label :users %>
      <br/>
      <% @users.each do |user| %>
          <div>
            <%= check_box_tag "book[user_ids][]", user.id, @book.users.include?(user) %>
            <%= user.email %>
          </div>
      <% end %>
    </div>
    <div class="actions">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
<% end %>

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/views/books/edit.html.erb
<h1><%= t 'views.book.edit.title' %></h1>

<%= render 'form' %>

<%= button_to I18n.t('views.back'), @book, method: :get, :class => "btn" %>

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/views/books/index.html.erb
<h1><%= t 'views.book.index.title' %></h1>

<div class="panel panel-default">
  <div class="panel-heading p">
    Suche Bücher
    <div class="btn-group btn-group-xs pull-right">
      <button id="btn_simple" type="button" class="btn btn-default btn-info">Einfach</button>
      <button id="btn_advanced" type="button" class="btn btn-default">Erweitert</button>
    </div>
  </div>
  <div id="div_search" class="panel-body">
    <div id="div_simple" class="input-group input-group-sm">
      <span class="input-group-btn">
        <button id="simple_btn_del" class="btn btn-default btn-danger" type="button">x</button>
      </span>
      <input id="simple_text" type="text" class="form-control" />
      <span class="input-group-btn">
        <button id="simple_go" class="btn btn-default btn-success" type="button">Go!</button>
      </span>
    </div>

    <div id="div_advanced0" class="input-group input-group-sm search-adv">
      <span class="input-group-btn">
        <button id="adv_btn_del" class="btn btn-default btn-danger" type="button">x</button>
      </span>
      <select id="adv_sel_col" class="form-control">
        <option value="0">Titel</option>
        <option value="1">Auflage</option>
        <option value="2">Veröffentlichungsdatum</option>
        <option value="3">Genre</option>
        <option value="4">Tags</option>
        <option value="5">Autoren</option>
      </select>
      <span class="input-group-btn" style="width:5px;"></span>
      <select id="adv_sel_op" class="form-control">
        <option value="0">enthält</option>
        <option value="1">enthält nicht</option>
        <option value="2">gleich</option>
        <option value="3">ungleich</option>
        <option value="4">größer als</option>
        <option value="5">kleiner als</option>
        <option value="6">vor</option>
        <option value="7">nach</option>
      </select>
      <span class="input-group-btn" style="width:5px;"></span>
      <input id="adv_text" type="text" class="form-control" />
    </div>

    <div id="div_advancedGo" class="btn-group btn-group-sm" style="margin-top: 3px;">
      <button id="btn_plus" class="btn btn-default btn-warning" type="button">
        +
      </button>
      <button id="adv_go" class="btn btn-default btn-success" type="button">
        Go!
      </button>
    </div>
  </div>

<table id="table_show_books" class="table table-striped">
  <thead>
    <tr>
      <th><%= Book.human_attribute_name(:title) %></th>
      <th><%= Book.human_attribute_name(:edition) %></th>
      <th><%= Book.human_attribute_name(:published) %></th>
      <th><%= Book.human_attribute_name(:genre) %></th>
      <th><%= Book.human_attribute_name(:tags) %></th>
      <th><%= Book.human_attribute_name(:users) %></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book, {:class=>"tbl_link"} %></td>
        <td><%= book.edition %></td>
        <td><%= book.published %></td>
        <td><%= book.genre %></td>
        <td><%= book.tags %></td>
        <td><%= book.users_list %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= button_to I18n.t('views.book.index.new'), new_book_path, method: :get, :class => "btn btn-primary" %>

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/views/books/new.html.erb
<h1><%= t 'views.book.new.title' %></h1>

<%= render 'form' %>

<%= button_to I18n.t('views.back'), books_path, method: :get, :class => "btn" %>

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/views/books/print.pdf.erb
<div class="cover">
  <p class="title"><%= @book.title %></p>

  <p class="authors"><%= @book.users_list_real_names %></p>

  <br/><br/>

  <p><%= "#{@book.edition}. #{Book.human_attribute_name(:edition)}" %></p>

  <% if @book.published? %>
      <p><%= "#{I18n.t('views.book.export.published_on')} #{@book.published.to_s}" %></p>
  <% end %>
</div>

<div class="chapter">
  <h1><%= Book.human_attribute_name(:abstract) %></h1>

  <p><%= raw @book.abstract %></p>
</div>

<% if @book.has_chunks? %>
    <% @book.chunks.each do |chunk| %>
        <div class="chapter">
          <h1><%= chunk.title %></h1>
          <%= raw chunk.content %>
        </div>
    <% end %>
<% end %>

WebEngProjekt_GemeinsamEinfallslos_Erweiterte Version/BookWriter/app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<p>
  <b><%= Book.human_attribute_name(:edition) %>:</b>
  <%= @book.edition %>
</p>

<% if @book.published? %>
    <p>
      <b><%= Book.human_attribute_name(:published) %>:</b>
      <%= @book.published %>
    </p>
<% end %>

<p>
  <b><%= Book.human_attribute_name(:genre) %>:</b>
  <%= @book.genre %>
</p>

<p>
  <b><%= Book.human_attribute_name(:tags) %>:</b>
  <%= @book.tags %>
</p>

<p>
  <b><%= Book.human_attribute_name(:users) %>:</b>
  <%= @book.users_list %>
</p>

<div class="horizontal">
  <% unless @book.closed? %>
      <%= button_to I18n.t('views.edit'), edit_book_path(@book), method: :get, :class => "btn btn-primary" %>
      <%= button_to I18n.t('views.book.close.close_book'), close_book_path(@book), data: {confirm: I18n.t('views.book.close.sure')}, :class => "btn btn-success" %>
  <% end %>
  <%= button_to I18n.t('views.book.new_edition'), new_edition_book_path(@book), method: :get, :class => "btn btn-primary" %>
  <%= button_to I18n.t('views.book.export.pdf'), print_book_path(@book, :format => 'pdf'), method: :get, :class => "btn btn-info" %>
  <%= button_to I18n.t('views.destroy'), @book, method: :delete, data: {confirm: I18n.t('views.are_you_sure')}, :class => "btn btn-danger" %>
</div>

<br/><br/><br/>

<h2><%= t 'views.chunk.index.title' %></h2>
<% if @book.has_chunks? %>
    <table id="table_show_bookchunks" class="table table-striped">
      <thead>
        <tr>
          <th><%= Chunk.human_attribute_name(:title) %></th>
          <th><%= Chunk.human_attribute_name(:section) %></th>
          <th><%= Chunk.human_attribute_name(:user) %></th>
          <th><%= Chunk.human_attribute_name(:version) %></th>
          <% unless @book.closed? %>
              <th></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
      <% @book.chunks.each do |chunk| %>
          <tr>
            <td><%= link_to chunk.title, @book.closed? ? book_chunk_path(@book, chunk) : edit_book_chunk_path(@book, chunk), {:class => "tbl_link"} %></td>
            <td><%= chunk.section %></td>
            <td><%= chunk.username %></td>
            <td><%= chunk.versions.last.id unless chunk.versions == nil %></td>
            <% unless @book.closed? %>
                <td><%= button_to I18n.t('views.destroy'), book_chunk_path(@book, chunk), method: :delete, data: {confirm: I18n.t('views.are_you_sure')} %> </td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <p><%= I18n.t('views.chunk.index.empty') %></p>
<% end %>

<br/>

<% unless @book.closed? %>
    <%= button_to I18n.t('views.chunk.index.new'), new_book_chunk_path(@book), method: :get, :class => "btn btn-primary" %>
<% end %>

<br/><br/>

<%= button_to I18n.t('views.back'), books_path, method: :get, :class => "btn" %>